version: '3'
services:
  admin-ui:
    build:
      context: ./frontend-admin
    ports:
      - "3000:3000"
    container_name: admin-ui
    stdin_open: true
    volumes:
       - ./frontend-admin:/usr/src/app/frontend-admin
       - /usr/src/app/frontend-admin/node_modules
  nodejs-server:
    build:
      context: ./backend
    ports:
      - "3007:3007"
    links:
        - mongo
    container_name: node-api
    volumes:
       - ./backend:/usr/src/app/backend
       - /usr/src/app/backend/node_modules
  mongo:
        container_name: mongo
        image: mongo
        volumes:
          - ./data:/data/db
        ports:
          - "27017:27017"    